force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/recordTypes/Admin.recordType-meta.xml
<RecordType>
    <fullName>Admin</fullName>
    <active>true</active>
    <label>Admin</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/NumberOfTickets__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTickets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsLeft__c.field-meta.xml
<CustomField>
    <fullName>TicketsLeft__c</fullName>
    <formula>NumberOfTickets__c  - TicketsSold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tickets Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsSold__c.field-meta.xml
<CustomField>
    <fullName>TicketsSold__c</fullName>
    <label>Tickets Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EV_TicketsController.cls
/*
* @author Alex D
* @date July 2020
* @description Ticket Container server side controller
*/
public class EV_TicketsController{

    @AuraEnabled
    public static InitializationWrapper getTickets(String eventId){

        List<Ticket__c> ticketList = new List<Ticket__c>();
        if (eventId != null)
            ticketList = [SELECT Id, NumberOfTickets__c, Name, TicketsLeft__c, TicketsSold__c 
                                          FROM Ticket__c WHERE Event__c =: eventId];
        
        String recTypeId = Schema.SObjectType.Attendee__c.getRecordTypeInfosByName().get('Admin').getRecordTypeId();

        return new InitializationWrapper(ticketList, recTypeId);

    }

    public class InitializationWrapper{
        @AuraEnabled
        public List<Ticket__c> ticketList {get;set;}
        @AuraEnabled
        public String AttendeeRTypeId {get;set;}

        public InitializationWrapper(List<Ticket__c> tList, String rType){
            this.ticketList = tList;
            this.AttendeeRTypeId = rType;
        }
    }

}