force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/TicketString__c.field-meta.xml
<CustomField>
    <fullName>TicketString__c</fullName>
    <label>Ticket String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/NumberOfTickets__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTickets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsLeft__c.field-meta.xml
<CustomField>
    <fullName>TicketsLeft__c</fullName>
    <formula>NumberOfTickets__c  - TicketsSold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tickets Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsSold__c.field-meta.xml
<CustomField>
    <fullName>TicketsSold__c</fullName>
    <label>Tickets Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EV_AttendeesServiceTest.cls
@isTest
public class EV_AttendeesServiceTest{

    @TestSetup
    static void makeData(){
        
        Event__c event = new Event__c(
            Name='test Event');
        insert event;

        Ticket__c ticket = new Ticket__c(
            Event__c = event.Id,
            NumberOfTickets__c = 10
        );
        insert ticket;
    }

    @IsTest
    static void testTicketUpdate(){

        Event__c event = [SELECT Id FROM Event__c LIMIT 1];
        Ticket__c ticket = [SELECT Id FROM Ticket__c LIMIT 1];

        test.startTest();

        Attendee__c attendee = new Attendee__c(
            Event__c = event.Id, 
            LastName__c = 'test', 
            Email__c = 'test@test.com',
            TicketString__c = ticket.Id + ':2');
        insert attendee;

        test.stoptest();

        Ticket__c ticketResult = [SELECT Id, TicketsSold__c, TicketsLeft__c FROM Ticket__c WHERE Id =: ticket.Id];
        system.assertEquals(ticketResult.TicketsSold__c, 2);
        system.assertEquals(ticketResult.TicketsLeft__c, 8);

    }

    @IsTest
    static void testContactUpsert(){

        Event__c event = [SELECT Id FROM Event__c LIMIT 1];

        test.startTest();

        Attendee__c attendee = new Attendee__c(
            Event__c = event.Id,
            FirstName__c = 'alex', 
            LastName__c = 'test', 
            Email__c = 'test@test.com');
        insert attendee;

        test.stoptest();

        List<Contact> cnt = [SELECT Id, FirstName, LastName FROM Contact WHERE Email =: attendee.Email__c];
        if (cnt.size() != 0){

            system.assertEquals(cnt.get(0).LastName, 'test');
            system.assertEquals(cnt.get(0).FirstName, 'alex');

            Attendee__c attendee2 = new Attendee__c(
                Event__c = event.Id,
                FirstName__c = 'test', 
                LastName__c = 'test', 
                Email__c = 'test@test.com');
            insert attendee2;

            List<Contact> cnt2 = [SELECT Id, FirstName, LastName FROM Contact WHERE Email =: attendee.Email__c];

            system.assertEquals(cnt2.get(0).LastName, 'test');
            system.assertEquals(cnt2.get(0).FirstName, 'test');

        }

    }

}