force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/TicketString__c.field-meta.xml
<CustomField>
    <fullName>TicketString__c</fullName>
    <label>Ticket String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Attendee_To_Contact_fields__mdt/Attendee_To_Contact_fields__mdt.object-meta.xml
<CustomObject>
    <description>Defines which fields will be synced between Attendee and Contact</description>
    <label>Attendee To Contact fields</label>
    <pluralLabel>Attendee To Contact fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Attendee_To_Contact_fields__mdt/fields/AttendeeAPIName__c.field-meta.xml
<CustomField>
    <fullName>AttendeeAPIName__c</fullName>
    <label>Attendee API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee_To_Contact_fields__mdt/fields/ContactAPIName__c.field-meta.xml
<CustomField>
    <fullName>ContactAPIName__c</fullName>
    <label>Contact API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsLeft__c.field-meta.xml
<CustomField>
    <fullName>TicketsLeft__c</fullName>
    <formula>NumberOfTickets__c  - TicketsSold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tickets Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/TicketsSold__c.field-meta.xml
<CustomField>
    <fullName>TicketsSold__c</fullName>
    <label>Tickets Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EV_AttendeesService.cls
/*
* @author Alex D
* @date July 2020
* @description Handler class for the Attendee trigger
*/
public with sharing class EV_AttendeesService{

    public static void updateTickets(List<Attendee__c> newList){

        Map<Id, Integer> usedTickets = new Map<Id, Integer>();
        Set<Id> eventSet = new Set<Id>();
        Map<Id, Attendee__c> attendeeMap = new Map<Id, Attendee__c>();
        //get Ticket info
        for (Attendee__c attendee : newList){
            if (attendee.TicketString__c != null){
                for (String s : attendee.TicketString__c.split(',')){
                    usedTickets.put(s.split(':').get(0), Integer.valueOf(s.split(':').get(1)));
                    attendeeMap.put(s.split(':').get(0), attendee);
                }
                eventSet.add(attendee.Event__c);
            }
        }

        if (eventSet.size() != 0){

            //update tickets remaining based on current attendee's selections
            List<Ticket__c> ticketsToUpdate = new List<Ticket__c>();
            for (Ticket__c ticket : [SELECT Id, TicketsLeft__c, TicketsSold__c FROM Ticket__c WHERE Event__c IN : eventSet]){
                if (ticket.TicketsSold__c == null)
                    ticket.TicketsSold__c = 0;
                if (usedTickets.containsKey(ticket.Id)){
                    if (ticket.TicketsLeft__c >= usedTickets.get(ticket.Id)){
                        ticket.TicketsSold__c += usedTickets.get(ticket.Id);
                        ticketsToUpdate.add(ticket);
                    }
                    else if (attendeeMap.containsKey(ticket.Id))
                        attendeeMap.get(ticket.Id).addError('There is an issue with the number of tickets. Please contact Support');

                }
                    
            }

            update ticketsToUpdate;

        }

    }

    public static void manageContacts(List<Attendee__c> newList){

        Map<String, Set<Id>> emailMap = new Map<String, Set<Id>>();
        for (Attendee__c attendee : newList){
            if (!emailMap.containsKey(attendee.Email__c))
                emailMap.put(attendee.Email__c, new Set<Id>{attendee.Id});
            else 
                emailMap.get(attendee.Email__c).add(attendee.Id);
        }

        if (emailMap.keySet().size() != 0){
            //get existing contacts by attendee email
            Map<String, Contact> contactByEmail = new Map<String, Contact>();
            Set<String> emailSet = new Set<String>();
            emailSet = emailMap.keySet();
            String contactQuery = 'SELECT Id, Email';
            for (Attendee_To_Contact_fields__mdt mdt : [SELECT Id, ContactAPIName__c FROM Attendee_To_Contact_fields__mdt])
                contactQuery += ', ' + mdt.ContactAPIName__c;
            contactQuery += ' FROM Contact WHERE Email IN : emailSet';
            for (Contact cnt : database.query(contactQuery)){
                contactByEmail.put(cnt.Email, cnt);
            }

            List<Contact> contactsToUpsert = new List<Contact>();
            Set<Id> attendeeSet = new Set<Id>();
            for (Attendee__c attendee : newList){
                Contact cnt;
                //if contacts does not exist
                if (!contactByEmail.containsKey(attendee.Email__c)){
                    cnt = new Contact(Email = attendee.Email__c);
                    contactByEmail.put(cnt.Email, cnt);
                }
                //if contact exists
                else
                    cnt = contactByEmail.get(attendee.Email__c);
                
                //upsert contact fields based on custom metadata type
                for (Attendee_To_Contact_fields__mdt mdt : [SELECT Id, ContactAPIName__c, AttendeeAPIName__c FROM Attendee_To_Contact_fields__mdt])
                    cnt.put(mdt.ContactAPIName__c, attendee.get(mdt.AttendeeAPIName__c));
                contactsToUpsert.add(cnt);
                attendeeSet.add(attendee.Id);
            }

            upsert contactsToUpsert;

            //parent new attendees after contact gets created
            List<Attendee__c> attendeesToUpdate = new List<Attendee__c>();
            for (Attendee__c attendee : [SELECT Id, Email__c, Contact__c FROM Attendee__c WHERE Id IN : attendeeSet]){
                if (contactByEmail.containsKey(attendee.Email__c)){
                    attendee.Contact__c = contactByEmail.get(attendee.Email__c).Id;
                    attendeesToUpdate.add(attendee);
                }
            }

            update attendeesToUpdate;
        }

    }

}