force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EV_ViewAttendeesControllerTest.cls
@isTest
public class EV_ViewAttendeesControllerTest{

    @TestSetup
    static void makeData(){
        
        Event__c event = new Event__c(
            Name='test Event');
        insert event;

        Attendee__c attendee = new Attendee__c(
            Event__c = event.Id, 
            LastName__c = 'test', 
            Email__c = 'test@test.com');
        insert attendee;

    }

    @IsTest
    static void testAttendeeQuery(){
        
        Event__c event = [SELECT Id FROM Event__c LIMIT 1];

        Test.startTest();

        EV_ViewAttendeesController.AttendeeDetails att = EV_ViewAttendeesController.getAttendees('TrueEvents__attendee__c', 'TrueEvents__AttendeeModalSet', event.Id);

        Test.stopTest();

        system.assertEquals(((List<Attendee__c>)att.lstOfSObjs).get(0).LastName__c, 'test');


        
    }

}