force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <label>Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/NumberOfTickets__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTickets__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EV_TicketsControllerTest.cls
@isTest
public class EV_TicketsControllerTest{

    @TestSetup
    static void makeData(){
        
        Event__c event = new Event__c(
            Name='test Event');
        insert event;

        Ticket__c ticket = new Ticket__c(
            Event__c = event.Id,
            NumberOfTickets__c = 10
        );
        insert ticket;
    }

    @IsTest
    static void testTicketQuery(){

        Event__c event = [SELECT Id FROM Event__c LIMIT 1];

        test.startTest();

        EV_TicketsController.InitializationWrapper wrap = EV_TicketsController.getTickets(event.Id);

        test.stopTest();

         system.assertEquals(wrap.ticketList.get(0).NumberOfTickets__c, 10);

    }

}